### ISSUE TITLE
Dendrogram for Louvain clusters

### ISSUE THREAD

**Issue by sunhyelee** [whtns/seuratTools#19]
Would it be possible to get dendrogram from Louvain cluster? As far as I understand, Louvain is based on Graph clustering representing non-linear structure, so I assume that it might not be possible, but I'd like to ask you just in case.

**Comment by whtns** [comment]
It's not possible to assign a dendrogram based on louvain clustering; see here for reference https://osca.bioconductor.org/clustering.html
