### ISSUE TITLE
Error when attempting to run "seu_complex_heatmap" command

### ISSUE THREAD

**Issue by JohnPatrickClearyJr** [whtns/seuratTools#26]
I recently installed the seuratTools package as an attempt to streamline using Seurat and ComplexHeatmap together. However when I attempt to run the seu_complex_heatmap command I am met with the following error:

~~~~~~~~~~
Error in as_mapper(.f, ...) : object 'set_names' not found
4.as_mapper(.f, ...)
3.purrr::map2(., ha_col_names.factor, set_names)
2.purrr::map(ha_col_names.factor, ~(scales::hue_pal())(length(.x))) %>% purrr::map2(ha_col_names.factor, set_names)
1.seu_complex_heatmap(oxy_rat_na, features = genes, group.by = "sample_condition")
~~~~~~~~~~

Any advice as to how to fix this issue would be very appreciated. For reference, my data is a standard Seurat object and I am specifying a list of genes that the heatmap is meant to visualize. The commands I am using are as follows:

~~~~~~~~~~
genes <- c("List_of_Genes")
seu_complex_heatmap(seurat_object, features=genes, group.by="sample_condition")
~~~~~~~~~~

Where "sample_condition" is the metadata slot I want my columns to be grouped by. Thank you in advance for whatever help can be offered.

**Comment by whtns** [comment]
hmm, sorry this looks like a bug, I should specify `purrr::set_names` will fix
